[package]
name = "bmfa"
version = "0.3.8"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
zip = "0.5.2"
