[package]
name = "bmfa"
version = "0.3.3"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.0"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
zip = "0.5.0"
